# Auditoria de codigo_cvm por Ticker (2010–2025)

Este notebook audita, ticker a ticker, se o `codigo_cvm` atribuído está correto — e se há demonstrativos financeiros suficientes para usá-lo. A auditoria funciona como um funil: a cada camada, os tickers que já têm evidência suficiente são **descartados** (dados como resolvidos) e só os que sobram seguem para a camada seguinte. A cada etapa o notebook imprime:

- os tickers descartados nesta camada, com a evidência que sustentou a decisão;
- a tabela dos tickers que ainda restam a conferir.

Nenhum arquivo é gerado até a consolidação final.

**Camadas:**
1. **FCA** (Formulário Cadastral) — fonte primária: CNPJ ↔ ticker ↔ `codigo_cvm`, ano a ano.
2. **Cadastro geral de companhias abertas** (`cad_cia_aberta.csv`) — fonte de apoio para quem sobrou da Camada 1.
3. **Cobertura de demonstrativos (DFP/ITR)** — mesmo com `codigo_cvm` correto, verifica se existe demonstrativo para montar os indicadores no período.

**Sobre a Camada 3:** a exploração de formato, colunas e inconsistências dos arquivos DFP/ITR baixados **não é feita aqui**. Isso já foi tratado em `02_data_understanding.ipynb`. Este notebook apenas consome o resultado dessa exploração (um inventário de pares `codigo_cvm` x ano já extraído e validado) e valida que o contrato de entrada esperado (colunas, tipos) está sendo cumprido antes de seguir.

## Setup

Funções utilitárias usadas em todas as camadas: normalização de `codigo_cvm`, normalização de nome para comparação fuzzy, e um loader genérico para os CSVs anuais da CVM (todos seguem o mesmo layout: `;`, latin1, ano no nome do arquivo).

In [59]:
try:
    from rapidfuzz import fuzz
except ImportError:
    import subprocess, sys
    subprocess.run([sys.executable, "-m", "pip", "install", "rapidfuzz", "--break-system-packages"])
    from rapidfuzz import fuzz

import pandas as pd
import glob
import os
import re
from pathlib import Path
import unicodedata

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 60)

caminho_atual = Path.cwd()
pasta_anterior = caminho_atual.parent


def normalizar_cvm(valor):
    """Remove zeros à esquerda e espaços, tratando codigo_cvm como número quando possível."""
    if valor is None:
        return None
    valor = str(valor).strip()
    if valor == "" or valor.upper() == "NAN":
        return None
    try:
        return str(int(valor))
    except ValueError:
        return valor


def normalizar_nome(nome):
    if not isinstance(nome, str):
        return ""
    nome = unicodedata.normalize("NFKD", nome).encode("ascii", "ignore").decode("utf-8")
    nome = re.sub(r"[^A-Za-z0-9 ]", " ", nome)
    nome = re.sub(r"\s+", " ", nome).strip().upper()
    return nome


def melhor_score_nome(nome_base, nome_alvo):
    """Combina 3 métricas de similaridade (rapidfuzz) para lidar bem com nome
    curto/coloquial (ex: NOMRES do COTAHIST) vs razão social oficial e completa."""
    if not isinstance(nome_alvo, str) or nome_alvo == "" or not isinstance(nome_base, str):
        return 0
    a, b = normalizar_nome(nome_base), normalizar_nome(nome_alvo)
    return max(
        fuzz.token_set_ratio(a, b),
        fuzz.partial_ratio(a, b),
        fuzz.token_sort_ratio(a, b),
    )


def carregar_arquivos_cvm(padrao_glob):
    """Lê e concatena um conjunto de CSVs anuais da CVM (mesmo layout)."""
    arquivos = sorted(glob.glob(padrao_glob))
    if not arquivos:
        raise FileNotFoundError(f"Nenhum arquivo encontrado para: {padrao_glob}")
    frames = []
    for arq in arquivos:
        df = pd.read_csv(arq, sep=";", encoding="latin1", dtype=str)
        df["arquivo_ano"] = os.path.basename(arq).split("_")[-1].replace(".csv", "")
        frames.append(df)
    return pd.concat(frames, ignore_index=True)

## Passo 0 — Ponto de partida: a tabela completa de tickers

Carrega `ticker_and_code_cvm_mapping.csv` sem cruzar com nada ainda. Este é o "estado zero" do funil: todos os tickers começam como pendentes de verificação. A tabela completa fica visível aqui para referência das próximas etapas.

In [60]:
caminho_mapping = pasta_anterior / "data/interim/05_ticker_and_code_cvm_mapping.csv"

seu_df = pd.read_csv(caminho_mapping, sep=";", dtype=str)
seu_df["TICKER"] = seu_df["TICKER"].str.strip().str.upper()
seu_df["codigo_cvm"] = seu_df["codigo_cvm"].astype(str).str.strip()
seu_df["primeiro_ano_observado"] = seu_df["primeiro_ano_observado"].astype(int)
seu_df["ultimo_ano_observado"] = seu_df["ultimo_ano_observado"].astype(int)
seu_df["codigo_cvm_norm"] = seu_df["codigo_cvm"].apply(normalizar_cvm)

print(f"Total de tickers a auditar: {len(seu_df)}")
seu_df

Total de tickers a auditar: 769

,TICKER,codigo_cvm,codigo_isin,NOMRES,primeiro_ano_observado,ultimo_ano_observado,codigo_cvm_norm
0,AALR3,24058,BRAALRACNOR6,ALLIAR,2016,2025,24058
1,ABCB4,20958,BRABCBACNPR4,ABC BRASIL,2010,2025,20958
2,ABEV3,23264,BRABEVACNOR1,AMBEV S/A,2013,2025,23264
3,ABNB3,20028,BRABNBACNOR4,ABNOTE,2010,2010,20028
4,ABRE11,22551,BRABRECDAM15,ABRIL EDUCA,2011,2014,22551
...,...,...,...,...,...,...,...
764,WIZS3,23590,BRWIZSACNOR1,WIZ S.A.,2017,2023,23590
765,WLMM3,11070,BRWLMMACNOR6,WLM IND COM,2018,2025,11070
766,WLMM4,11070,BRWLMMACNPR3,WLM IND COM,2017,2025,11070
767,YDUQ3,21016,BRYDUQACNOR3,YDUQS PART,2019,2025,21016
768,ZAMP3,24317,BRZAMPACNOR5,ZAMP S.A.,2022,2025,24317

## Passo 1 — Carregar referência FCA

Une `fca_cia_aberta_valor_mobiliario_AAAA.csv` (ticker ↔ CNPJ ↔ período de negociação) com `fca_cia_aberta_geral_AAAA.csv` (CNPJ ↔ `codigo_cvm` ↔ nome, ano a ano) para montar, por ticker, o conjunto de `codigo_cvm` que já esteve associado a ele — junto com o ano de cada associação (`candidatos_por_ano`). Isso permite checar depois se o código estava vigente **no período em que o ticker foi de fato negociado**, e não em qualquer ano da história do FCA.

In [61]:
diretorio_fca = pasta_anterior / "data/raw/06_fca_extracted"

fca_vm = carregar_arquivos_cvm(os.path.join(diretorio_fca, "fca_cia_aberta_valor_mobiliario_*.csv"))
fca_vm["CNPJ_Companhia"] = fca_vm["CNPJ_Companhia"].str.replace(r"\D", "", regex=True)
fca_vm["Codigo_Negociacao"] = fca_vm["Codigo_Negociacao"].str.strip().str.upper()
fca_vm["Data_Inicio_Negociacao"] = pd.to_datetime(fca_vm["Data_Inicio_Negociacao"], errors="coerce")
fca_vm["Data_Fim_Negociacao"] = pd.to_datetime(fca_vm["Data_Fim_Negociacao"], errors="coerce")
fca_vm = fca_vm[fca_vm["Codigo_Negociacao"].notna() & (fca_vm["Codigo_Negociacao"] != "")].copy()

fca_geral = carregar_arquivos_cvm(os.path.join(diretorio_fca, "fca_cia_aberta_geral_*.csv"))
fca_geral["CNPJ_Companhia"] = fca_geral["CNPJ_Companhia"].str.replace(r"\D", "", regex=True)
fca_geral["Codigo_CVM"] = fca_geral["Codigo_CVM"].astype(str).str.strip()
fca_geral["Data_Referencia"] = pd.to_datetime(fca_geral["Data_Referencia"], errors="coerce")
fca_geral["Nome_Empresarial"] = fca_geral["Nome_Empresarial"].str.strip()
fca_geral["Nome_Empresarial_Anterior"] = fca_geral["Nome_Empresarial_Anterior"].str.strip()

print("FCA valor mobiliário — linhas ticker x CNPJ x período:", len(fca_vm))
print("FCA geral — linhas CNPJ x codigo_cvm x ano:", len(fca_geral))

ref_cnpj_cvm = (
    fca_geral[["CNPJ_Companhia", "Codigo_CVM", "Nome_Empresarial", "Nome_Empresarial_Anterior", "Data_Referencia"]]
    .dropna(subset=["CNPJ_Companhia", "Codigo_CVM"])
    .drop_duplicates()
    .sort_values(["CNPJ_Companhia", "Data_Referencia"])
)
ref_cnpj_cvm["ano_referencia"] = ref_cnpj_cvm["Data_Referencia"].dt.year

n_cvm_por_cnpj = ref_cnpj_cvm.groupby("CNPJ_Companhia")["Codigo_CVM"].nunique()
print("CNPJs com mais de um codigo_cvm distinto ao longo do tempo:", (n_cvm_por_cnpj > 1).sum(), "de", len(n_cvm_por_cnpj))


def data_compativel(row):
    if pd.isna(row["Data_Referencia"]):
        return False
    inicio = row["Data_Inicio_Negociacao"]
    fim = row["Data_Fim_Negociacao"] if pd.notna(row["Data_Fim_Negociacao"]) else pd.Timestamp("2100-01-01")
    if pd.isna(inicio):
        return True
    return inicio <= row["Data_Referencia"] <= fim


fca_vm_reduzido = fca_vm[["CNPJ_Companhia", "Codigo_Negociacao", "Data_Inicio_Negociacao", "Data_Fim_Negociacao"]].copy()
ref_ticker_cvm = fca_vm_reduzido.merge(ref_cnpj_cvm, on="CNPJ_Companhia", how="left")
ref_ticker_cvm["compativel"] = ref_ticker_cvm.apply(data_compativel, axis=1)
ref_ticker_cvm = ref_ticker_cvm[ref_ticker_cvm["compativel"]].copy()


def nomes_unicos(serie_atual, serie_anterior):
    nomes = set(serie_atual.dropna()) | set(serie_anterior.dropna())
    return sorted(n for n in nomes if n)


ref_ticker_cvm_final = (
    ref_ticker_cvm
    .groupby("Codigo_Negociacao")
    .apply(lambda g: pd.Series({
        "codigo_cvm_fca": sorted(set(g["Codigo_CVM"])),
        "nome_empresarial_fca": nomes_unicos(g["Nome_Empresarial"], g["Nome_Empresarial_Anterior"]),
        "candidatos_por_ano": sorted(set(zip(g["ano_referencia"].dropna().astype(int), g["Codigo_CVM"]))),
    }))
    .reset_index()
    .rename(columns={"Codigo_Negociacao": "TICKER"})
)

print("\nTotal de tickers com alguma referência no FCA:", len(ref_ticker_cvm_final))

FCA valor mobiliário — linhas ticker x CNPJ x período: 4427
FCA geral — linhas CNPJ x codigo_cvm x ano: 10955
CNPJs com mais de um codigo_cvm distinto ao longo do tempo: 6 de 1260

Total de tickers com alguma referência no FCA: 752

Alguns tickers do FCA são preenchidos com valores residuais que não correspondem a tickers reais da B3 (ex.: `-`, `0`, `00000`, `999999`) — resíduos de cadastro que não afetam a auditoria, pois só entram no cruzamento se existir um `TICKER` correspondente na sua tabela.

## Passo 2 — Camada 1: cruzar com o FCA e separar o funil

Classifica cada ticker em:

- **ALTA** (descartado, resolvido): o `codigo_cvm` informado bate com um candidato do FCA para aquele ticker, **e** o ano desse candidato está dentro do intervalo `primeiro_ano_observado`–`ultimo_ano_observado` medido no COTAHIST. Essa exigência de ano evita validar um código que só passou a valer depois (ou parou de valer antes) do período em que o ticker foi observado.
- **PENDENTE** (segue no funil): sem referência FCA, ou nenhum candidato compatível no período bate com o `codigo_cvm` informado.

Abaixo: os descartados com a evidência que embasou a decisão, e a tabela dos que restam para a Camada 2.

In [62]:
auditoria = seu_df.merge(ref_ticker_cvm_final, on="TICKER", how="left")


def status_layer1(row):
    candidatos = row["candidatos_por_ano"]
    if not isinstance(candidatos, list) or len(candidatos) == 0:
        return "PENDENTE", None
    alvo = row["codigo_cvm_norm"]
    for ano, cvm in candidatos:
        dentro_do_periodo = row["primeiro_ano_observado"] <= ano <= row["ultimo_ano_observado"]
        if dentro_do_periodo and normalizar_cvm(cvm) == alvo:
            return "ALTA", ano
    return "PENDENTE", None


resultado_layer1 = auditoria.apply(status_layer1, axis=1, result_type="expand")
auditoria["status_layer1"] = resultado_layer1[0]
auditoria["ano_confirmacao_fca"] = resultado_layer1[1]

print(auditoria["status_layer1"].value_counts())

descartados_fca = auditoria[auditoria["status_layer1"] == "ALTA"]
pendentes_pos_fca = auditoria[auditoria["status_layer1"] == "PENDENTE"].copy()

print(f"\n--- Descartados via FCA ({len(descartados_fca)}) ---")
display(descartados_fca[["TICKER", "codigo_cvm", "ano_confirmacao_fca", "nome_empresarial_fca",
                          "primeiro_ano_observado", "ultimo_ano_observado"]])

print(f"\n--- Restam para a Camada 2 ({len(pendentes_pos_fca)}) ---")
display(pendentes_pos_fca[["TICKER", "codigo_cvm", "codigo_isin", "primeiro_ano_observado",
                            "ultimo_ano_observado", "codigo_cvm_fca", "nome_empresarial_fca"]])

status_layer1
ALTA        544
PENDENTE    225
Name: count, dtype: int64

--- Descartados via FCA (544) ---

,TICKER,codigo_cvm,ano_confirmacao_fca,nome_empresarial_fca,primeiro_ano_observado,ultimo_ano_observado
0,AALR3,24058,2017.0,"[ALLIANÇA SAÚDE E PARTICIPAÇÕES S.A., CENTRO DE IMAGEM D...",2016,2025
1,ABCB4,20958,2010.0,"[BANCO ABC BRASIL S/A, BCO ABC BRASIL S.A., Banco ABC Ro...",2010,2025
2,ABEV3,23264,2014.0,"[AMBEV S.A., Ambev S.A., InBev Participações Societárias...",2013,2025
12,AELP3,19313,2010.0,"[AES ELPA S.A., AES ELPA SA, AES Elpa Ltda]",2010,2018
13,AERI3,25283,2021.0,[AERIS IND. E COM. DE EQUIP. PARA GER. DE ENG. S.A.],2020,2025
...,...,...,...,...,...,...
764,WIZS3,23590,2017.0,"[FPC PAR CORRETORA DE SEGUROS S.A., FPC Par Corretora de...",2017,2023
765,WLMM3,11070,2018.0,"[Supergasbras Indústria e Comércio S.A., WLM INDÚSTRIA E...",2018,2025
766,WLMM4,11070,2017.0,"[Supergasbras Indústria e Comércio S.A., WLM INDÚSTRIA E...",2017,2025
767,YDUQ3,21016,2019.0,"[ESTACIO PARTICIPACOES S.A., ESTACIO PARTICIPAÇÕES SA, Y...",2019,2025
768,ZAMP3,24317,2022.0,"[BK BRASIL OPERAÇÃO E ASSESSORIA A RESTAURANTES SA, CMNP...",2022,2025

--- Restam para a Camada 2 (225) ---

,TICKER,codigo_cvm,codigo_isin,primeiro_ano_observado,ultimo_ano_observado,codigo_cvm_fca,nome_empresarial_fca
3,ABNB3,20028,BRABNBACNOR4,2010,2010,NaN,NaN
4,ABRE11,22551,BRABRECDAM15,2011,2014,NaN,NaN
5,ABRE3,22551,BRABREACNOR9,2014,2015,NaN,NaN
6,ABYA3,20206,BRABYAACNOR3,2010,2010,NaN,NaN
7,ACGU3,20940,BRACGUACNOR6,2010,2010,NaN,NaN
...,...,...,...,...,...,...,...
743,VIVO4,17671,BRVIVOACNPR8,2010,2011,NaN,NaN
749,VTLM3,21725,BRVTLMACNOR3,2016,2016,NaN,NaN
756,WDCN3,25895,BRWDCNACNOR2,2025,2025,NaN,NaN
761,WISA3,14397,BRWISAACNOR4,2011,2012,NaN,NaN
762,WISA4,14397,BRWISAACNPR1,2011,2012,NaN,NaN

## Passo 3 — Camada 2: cruzar os pendentes com `cad_cia_aberta`

Para quem sobrou da Camada 1, verifica se o `codigo_cvm` informado existe no cadastro geral de companhias abertas da CVM e, se existir, compara `NOMRES` (nome curto do COTAHIST) com `DENOM_SOCIAL` (razão social oficial) usando o melhor entre 3 métricas de similaridade (`token_set_ratio`, `partial_ratio`, `token_sort_ratio`). Isso é necessário porque nomes curtos/coloquiais como "AMBEV" batem mal com razões sociais completas como "COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV" em métricas simples de distância de string.

Três desfechos:
- **ALTA_VIA_CADASTRO** (descartado): código existe e o nome bate (score ≥ `LIMIAR_NOME`).
- **REVISAR_NOME_DIVERGENTE** (segue no funil): código existe, mas o nome não bate.
- **REVISAR_CODIGO_INEXISTENTE** (segue no funil): o `codigo_cvm` nem existe no cadastro — sinal forte de erro de digitação/transcrição, ou caso atípico fora do registro padrão (ex.: BDR/unit).

**Nota:** o cadastro é reduzido a um registro por `codigo_cvm` mantendo a razão social mais recente (`keep="last"`). Isso significa que tickers antigos, cujo nome no COTAHIST reflete uma razão social já trocada há anos, tendem a cair em `REVISAR_NOME_DIVERGENTE` mesmo com o `codigo_cvm` correto — vale ter isso em mente ao revisar a lista, e considerar comparar contra o histórico de nomes se o volume de divergências por esse motivo for grande.

In [63]:
caminho_cad = pasta_anterior / "data/raw/06_cad_cia_aberta.csv"

cad = pd.read_csv(caminho_cad, sep=";", encoding="latin1", dtype=str)
cad.columns = [c.strip() for c in cad.columns]
cad["CD_CVM_NORM"] = cad["CD_CVM"].astype(str).str.strip().apply(normalizar_cvm)
cad["DENOM_SOCIAL"] = cad["DENOM_SOCIAL"].str.strip()
cad_unico = cad.drop_duplicates(subset="CD_CVM_NORM", keep="last")
print("Companhias únicas no cadastro:", len(cad_unico))

LIMIAR_NOME = 80

pendentes_pos_fca = pendentes_pos_fca.merge(
    cad_unico[["CD_CVM_NORM", "DENOM_SOCIAL"]],
    left_on="codigo_cvm_norm", right_on="CD_CVM_NORM", how="left"
)
pendentes_pos_fca["existe_no_cadastro"] = pendentes_pos_fca["DENOM_SOCIAL"].notna()
pendentes_pos_fca["score_nome_cadastro"] = pendentes_pos_fca.apply(
    lambda r: melhor_score_nome(r.get("NOMRES"), r["DENOM_SOCIAL"]) if r["existe_no_cadastro"] else 0,
    axis=1,
)


def status_layer2(row):
    if not row["existe_no_cadastro"]:
        return "REVISAR_CODIGO_INEXISTENTE"
    if row["score_nome_cadastro"] >= LIMIAR_NOME:
        return "ALTA_VIA_CADASTRO"
    return "REVISAR_NOME_DIVERGENTE"


pendentes_pos_fca["status_layer2"] = pendentes_pos_fca.apply(status_layer2, axis=1)
print(pendentes_pos_fca["status_layer2"].value_counts())

descartados_cadastro = pendentes_pos_fca[pendentes_pos_fca["status_layer2"] == "ALTA_VIA_CADASTRO"]
pendentes_pos_cadastro = pendentes_pos_fca[pendentes_pos_fca["status_layer2"] != "ALTA_VIA_CADASTRO"].copy()

print(f"\n--- Descartados via cadastro ({len(descartados_cadastro)}) ---")
display(descartados_cadastro[["TICKER", "codigo_cvm", "DENOM_SOCIAL", "score_nome_cadastro"]]
        .sort_values("score_nome_cadastro"))

print(f"\n--- Restam para revisão manual / Camada 3 ({len(pendentes_pos_cadastro)}) ---")
display(pendentes_pos_cadastro[["TICKER", "codigo_cvm", "status_layer2", "DENOM_SOCIAL", "score_nome_cadastro"]]
        .sort_values("score_nome_cadastro"))

Companhias únicas no cadastro: 2566
status_layer2
ALTA_VIA_CADASTRO             140
REVISAR_NOME_DIVERGENTE        84
REVISAR_CODIGO_INEXISTENTE      1
Name: count, dtype: int64

--- Descartados via cadastro (140) ---

,TICKER,codigo_cvm,DENOM_SOCIAL,score_nome_cadastro
10,AGEI3,21911,AGRE EMPREENDIMENTOS IMOBILIÁRIOS SA,80.000000
51,CAFE4,2062,CAFE SOLUVEL BRASILIA SA,80.000000
195,TCSL4,17639,TIM PARTICIPAÇÕES SA,80.000000
114,IMCH3,22438,"INTERNATIONAL MEAL COMPANY HOLDINGS, SA",80.000000
202,TLPP3,17671,TELEFÔNICA BRASIL S.A.,80.000000
194,TCSL3,17639,TIM PARTICIPAÇÕES SA,80.000000
203,TLPP4,17671,TELEFÔNICA BRASIL S.A.,80.000000
145,NORD3,9083,NORDON INDUSTRIAS METALURGICAS S.A.,82.352941
197,TENE5,11215,TECBLU - TECELAGEM BLUMENAU S/A.,83.333333
198,TENE7,11215,TECBLU - TECELAGEM BLUMENAU S/A.,83.333333
215,VAGR3,20354,TERRA SANTA AGRO S.A.,83.333333
169,RPMG4,9989,REFINARIA DE PETRÓLEOS DE MANGUINHOS S.A. - EM RECUPERAÇ...,83.333333
188,SUZB5,13986,SUZANO S.A.,84.210526
66,CSNA3,4030,CIA SIDERURGICA NACIONAL,85.714286
113,IMBI4,3174,CIA DOCAS DE IMBITUBA,86.956522
112,IMBI3,3174,CIA DOCAS DE IMBITUBA,86.956522
106,IENG3,16730,INEPAR ENERGIA SA,87.500000
98,GETT11,26140,GETNET ADQUIRÊNCIA E SERVIÇOS PARA MEIOS DE PAGAMENTO S.A.,87.500000
107,IENG5,16730,INEPAR ENERGIA SA,87.500000
99,GETT3,26140,GETNET ADQUIRÊNCIA E SERVIÇOS PARA MEIOS DE PAGAMENTO S.A.,87.500000
100,GETT4,26140,GETNET ADQUIRÊNCIA E SERVIÇOS PARA MEIOS DE PAGAMENTO S.A.,87.500000
56,CEAB3,24848,C&A MODAS S.A.,88.888889
204,TMAR3,11320,TELEMAR NORTE LESTE SA,90.000000
205,TMAR5,11320,TELEMAR NORTE LESTE SA,90.000000
123,KSSA3,20249,KLABIN SEGALL S/A,91.666667
62,CMIN3,25585,CSN MINERAÇÃO S.A.,91.666667
206,TNCP4,17604,TELE NORTE CELULAR PARTICIPAÇÕES SA,91.666667
92,FRAS4,6211,FRASLE MOBILITY S.A.,92.307692
5,ADHM3,21725,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,95.238095
24,AUTM3,22381,AUTOMETAL S/A,100.000000
16,ALUP4,21490,ALUPAR INVESTIMENTO S/A,100.000000
25,AVIL3,108,AÇOS VILLARES SA,100.000000
55,CCTY3,27570,BELORA RDVC CITY DESENVOLVIMENTO IMOBILIÁRIO S.A.,100.000000
53,CBMA4,4448,COBRASMA SA,100.000000
52,CBMA3,4448,COBRASMA SA,100.000000
46,BRPR3,19925,BR PROPERTIES S.A.,100.000000
37,BMTO3,1970,BRASMOTOR SA,100.000000
38,BMTO4,1970,BRASMOTOR SA,100.000000
36,BMGB11,24600,BANCO BMG S/A,100.000000
58,CLAN4,18490,CLARION S/A AGROINDUSTRIAL,100.000000
68,CTAX3,19100,CONTAX PARTICIPAÇÕES S.A. - EM RECUPERAÇÃO JUDICIAL,100.000000
69,CTAX4,19100,CONTAX PARTICIPAÇÕES S.A. - EM RECUPERAÇÃO JUDICIAL,100.000000
70,CTIP3,21792,CETIP S.A. - MERCADOS ORGANIZADOS,100.000000
71,CTPC3,12181,MARAMBAIA ENERGIA RENOVÁVEL SA,100.000000
63,CNFB4,4650,CONFAB INDUSTRIAL SA,100.000000
64,CPLE11,14311,COMPANHIA PARANAENSE DE ENERGIA COPEL,100.000000
65,CRUZ3,4057,SOUZA CRUZ SA,100.000000
67,CTAX11,19100,CONTAX PARTICIPAÇÕES S.A. - EM RECUPERAÇÃO JUDICIAL,100.000000
77,DROG3,5258,RAIA DROGASIL S.A.,100.000000
76,DOCA4,3182,DOCAS INVESTIMENTOS SA,100.000000
27,AXIA6,2437,AXIA ENERGIA S.A.,100.000000
26,AXIA3,2437,AXIA ENERGIA S.A.,100.000000
30,BEMA3,20656,BEMATECH S/A,100.000000
31,BHGR3,20907,BHG S.A. - BRAZIL HOSPITALITY GROUP,100.000000
34,BIOM4,19305,BIOMM SA,100.000000
29,BBTG11,22616,BANCO BTG PACTUAL S/A,100.000000
35,BISA3,20265,BROOKFIELD INCORPORAÇÕES S.A.,100.000000
17,AMAR3,22055,MARISA LOJAS SA,100.000000
18,AMBV3,18112,COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV,100.000000
4,ACGU3,20940,AÇUCAR GUARANI S/A,100.000000
7,AEDU11,18961,ANHANGUERA EDUCACIONAL PARTICIPAÇÕES S.A.,100.000000
8,AEDU3,18961,ANHANGUERA EDUCACIONAL PARTICIPAÇÕES S.A.,100.000000
9,AFLU3,20150,AFLUENTE GERAÇÃO DE ENERGIA ELÉTRICA S.A.,100.000000
3,ABYA3,20206,ABYARA PLANEJAMENTO IMOBILIÁRIO S/A,100.000000
102,GVTT3,20117,GVT HOLDING S/A,100.000000
95,GAZO4,6378,GAZOLA SA INDÚSTRIA METALURGICA,100.000000
96,GETI3,18970,AES TIETÊ ENERGIA S.A,100.000000
97,GETI4,18970,AES TIETÊ ENERGIA S.A,100.000000
84,ELPL5,14176,ELETROPAULO METROP. ELET. SAO PAULO S.A.,100.000000
85,ELPL6,14176,ELETROPAULO METROP. ELET. SAO PAULO S.A.,100.000000
86,EPAR3,15458,EMBPAR PARTICIPAÇÕES S/A,100.000000
91,FIEI3,20630,FICA EMPREENDIMENTOS IMOBILIARIOS S.A.,100.000000
83,ELPL4,14176,ELETROPAULO METROP. ELET. SAO PAULO S.A.,100.000000
81,EBTP4,17647,EMBRATEL PARTICIPAÇÕES SA,100.000000
80,EBTP3,17647,EMBRATEL PARTICIPAÇÕES SA,100.000000
79,DXTG4,14931,DIXIE TOGA SA,100.000000
72,CZRS4,20753,MASSA FALIDA DO BANCO CRUZEIRO DO SUL S/A,100.000000
73,DAYC4,20796,BANCO DAYCOVAL S.A.,100.000000
111,ILMD4,140,YARA BRASIL FERTILIZANTES,100.000000
104,HAGA4,13366,HAGA S.A. INDÚSTRIA E COMÉRCIO,100.000000
124,LEVE4,8575,MAHLE METAL LEVE S.A.,100.000000
128,LUXM4,8192,TREVISA INVESTIMENTOS SA,100.000000
131,MAPT4,13854,CEMEPE INVESTIMENTOS SA,100.000000
130,MAPT3,13854,CEMEPE INVESTIMENTOS SA,100.000000
133,MBRF3,20788,MARFRIG GLOBAL FOODS SA,100.000000
134,MEDI3,20273,MEDIAL SAUDE S/A,100.000000
137,MNDL4,5312,MUNDIAL S.A - PRODUTOS DE CONSUMO,100.000000
132,MARI3,20761,MARISA SA,100.000000
140,MRSL4,8486,MARISOL SA,100.000000
110,IGUA6,3336,CIA. IGUAÇU DE CAFÉ SOLÚVEL,100.000000
109,IGUA5,3336,CIA. IGUAÇU DE CAFÉ SOLÚVEL,100.000000
108,IGUA3,3336,CIA. IGUAÇU DE CAFÉ SOLÚVEL,100.000000
115,INEP4,7595,INEPAR S.A. INDUSTRIA E CONSTRUCOES EM RECUPERACAO JUDICIAL,100.000000
119,KLBN3,12653,KLABIN S.A.,100.000000
120,KLBN4,12653,KLABIN S.A.,100.000000
103,HAGA3,13366,HAGA S.A. INDÚSTRIA E COMÉRCIO,100.000000
154,PNOR5,9784,PRONOR PETROQUIMICA SA,100.000000
153,PMET6,1686,PRÓ METALURGIA SA - EM LIQUIDAÇÃO EXTRAJUDICIAL,100.000000
152,PMAM4,9393,PARANAPANEMA S.A. - EM RECUPERAÇÃO JUDICIAL,100.000000
151,PLAS3,13471,PLASCAR PARTICIPAÇÕES INDUSTRIAIS S.A,100.000000
146,OBTC3,27910,ORANJEBTC S.A. - EDUCAÇÃO E INVESTIMENTO,100.000000
144,NETC4,14621,NET SERVIÇOS DE COMUNICAÇÃO S.A.,100.000000
143,NETC3,14621,NET SERVIÇOS DE COMUNICAÇÃO S.A.,100.000000
155,PNOR6,9784,PRONOR PETROQUIMICA SA,100.000000
165,REEM4,12840,RIMET EMPREEND. INDS. E COMERCIAIS S/A,100.000000
166,RHDS3,14559,M&G POLIÉSTER SA,100.000000
158,PRVI3,20974,COMPANHIA PROVIDENCIA IND E COMERCIO,100.000000
157,PRTX3,21776,PORTX OPERAÇÕES PORTUÁRIAS S.A.,100.000000
161,RDCD3,20893,REDECARD S/A,100.000000
162,RDTR3,22128,REDENTOR ENERGIA S/A,100.000000
164,REDE4,3190,REDE ENERGIA PARTICIPAÇÕES S.A.,100.000000
160,RAIA3,22306,RAIA SA,100.000000
175,SANB4,20532,BANCO SANTANDER (BRASIL) S.A.,100.000000
174,SANB3,20532,BANCO SANTANDER (BRASIL) S.A.,100.000000
173,RVEE3,27650,REVEE S.A.,100.000000
172,RUMO3,23450,RUMO LOGÍSTICA OPERADORA MULTIMODAL S.A.,100.000000
171,RSIP4,18279,RASIP AGRO PASTORIL SA,100.000000
170,RSIP3,18279,RASIP AGRO PASTORIL SA,100.000000
181,SGEN4,10596,SERGEN SERVS GERAIS DE ENG SA,100.000000
176,SCLO4,3549,CIA INDUSTRIAL SCHLOSSER S.A.,100.000000
191,TAMM3,16390,TAM S.A.,100.000000
187,SULT4,13030,CONSTRUTORA SULTEPA S.A. - EM RECUPERAÇÃO JUDICIAL,100.000000
186,SULT3,13030,CONSTRUTORA SULTEPA S.A. - EM RECUPERAÇÃO JUDICIAL,100.000000
19,AMBV4,18112,COMPANHIA DE BEBIDAS DAS AMÉRICAS-AMBEV,100.000000
20,AMCE3,16195,AMERICEL SA,100.000000
21,AMIL3,21172,AMIL PARTICIPAÇÕES S/A,100.000000
23,ARTR3,19771,ARTERIS S.A.,100.000000
15,ALUP3,21490,ALUPAR INVESTIMENTO S/A,100.000000
199,TERI3,22136,TEREOS INTERNACIONAL S/A,100.000000
196,TEMP3,19917,TEMPO PARTICIPAÇOES S/A,100.000000
192,TAMM4,16390,TAM S.A.,100.000000
178,SFSA4,20680,BANCO SOFISA SA,100.000000
184,SMLE3,23140,SMILES S.A.,100.000000
210,TUPY4,6343,TUPY SA,100.000000
211,TVIT3,21768,"TIVIT TERCEIRIZAÇÃO DE PROCESSOS, SERVIÇOS E TECNOLOGIA S/A",100.000000
213,UGPA4,18465,ULTRAPAR PARTICIPAÇÕES SA,100.000000
216,VALE5,4170,VALE S.A.,100.000000
218,VINE5,5991,VICUNHA TEXTIL SA,100.000000
223,WISA3,14397,WIEST SA,100.000000
224,WISA4,14397,WIEST SA,100.000000

--- Restam para revisão manual / Camada 3 (85) ---

,TICKER,codigo_cvm,status_layer2,DENOM_SOCIAL,score_nome_cadastro
156,PPLA11,80152,REVISAR_CODIGO_INEXISTENTE,NaN,0.000000
220,VIVO4,17671,REVISAR_NOME_DIVERGENTE,TELEFÔNICA BRASIL S.A.,25.000000
219,VIVO3,17671,REVISAR_NOME_DIVERGENTE,TELEFÔNICA BRASIL S.A.,25.000000
82,ECOD3,20354,REVISAR_NOME_DIVERGENTE,TERRA SANTA AGRO S.A.,28.571429
200,TIBR5,11398,REVISAR_NOME_DIVERGENTE,TRONOX PIGMENTOS DO BRASIL S.A.,30.000000
201,TIBR6,11398,REVISAR_NOME_DIVERGENTE,TRONOX PIGMENTOS DO BRASIL S.A.,30.000000
129,LVTC3,25895,REVISAR_NOME_DIVERGENTE,LIVETECH DA BAHIA INDÚSTRIA E COMÉRCIO S.A.,33.333333
0,ABNB3,20028,REVISAR_NOME_DIVERGENTE,VALID SOLUÇÕES S.A.,33.333333
148,OHLB3,19771,REVISAR_NOME_DIVERGENTE,ARTERIS S.A.,33.333333
222,WDCN3,25895,REVISAR_NOME_DIVERGENTE,LIVETECH DA BAHIA INDÚSTRIA E COMÉRCIO S.A.,33.333333
189,SWET3,21725,REVISAR_NOME_DIVERGENTE,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,36.363636
101,GLOB3,6505,REVISAR_NOME_DIVERGENTE,GRUPO CASAS BAHIA S.A.,36.363636
50,BTTL4,15458,REVISAR_NOME_DIVERGENTE,EMBPAR PARTICIPAÇÕES S/A,36.363636
49,BTTL3,15458,REVISAR_NOME_DIVERGENTE,EMBPAR PARTICIPAÇÕES S/A,36.363636
6,ADMF3,27634,REVISAR_NOME_DIVERGENTE,B100 S.A.,37.500000
122,KROT3,17973,REVISAR_NOME_DIVERGENTE,COGNA EDUCAÇÃO S.A.,40.000000
121,KROT11,17973,REVISAR_NOME_DIVERGENTE,COGNA EDUCAÇÃO S.A.,40.000000
190,SZPQ4,4057,REVISAR_NOME_DIVERGENTE,SOUZA CRUZ SA,40.000000
105,HRTP3,22187,REVISAR_NOME_DIVERGENTE,PRIO S.A.,40.000000
168,RNAR3,19658,REVISAR_NOME_DIVERGENTE,MASSA FALIDA DE POMIFRUTAS S/A,40.000000
75,DMMO3,23493,REVISAR_NOME_DIVERGENTE,PRIO FORTE S.A.,40.000000
125,LFFE3,12262,REVISAR_NOME_DIVERGENTE,JPSP INVESTIMENTOS E PARTICIPAÇÕES S.A.,41.666667
48,BRTO4,11312,REVISAR_NOME_DIVERGENTE,OI S.A. - EM RECUPERAÇÃO JUDICIAL,41.666667
47,BRTO3,11312,REVISAR_NOME_DIVERGENTE,OI S.A. - EM RECUPERAÇÃO JUDICIAL,41.666667
185,STLB3,21725,REVISAR_NOME_DIVERGENTE,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,41.666667
126,LFFE4,12262,REVISAR_NOME_DIVERGENTE,JPSP INVESTIMENTOS E PARTICIPAÇÕES S.A.,41.666667
150,PCAR5,14826,REVISAR_NOME_DIVERGENTE,COMPANHIA BRASILEIRA DE DISTRIBUIÇÃO,43.478261
40,BNCA3,1023,REVISAR_NOME_DIVERGENTE,BANCO DO BRASIL S.A.,44.444444
147,OGSA3,23493,REVISAR_NOME_DIVERGENTE,PRIO FORTE S.A.,44.444444
193,TBLE3,17329,REVISAR_NOME_DIVERGENTE,ENGIE BRASIL ENERGIA S.A.,44.444444
14,ALLL4,17450,REVISAR_NOME_DIVERGENTE,RUMO S.A.,46.153846
12,ALLL11,17450,REVISAR_NOME_DIVERGENTE,RUMO S.A.,46.153846
13,ALLL3,17450,REVISAR_NOME_DIVERGENTE,RUMO S.A.,46.153846
116,INET3,15423,REVISAR_NOME_DIVERGENTE,FICTOR ALIMENTOS S.A. - EM RECUPERAÇÃO JUDICIAL,46.153846
136,MLFT4,8672,REVISAR_NOME_DIVERGENTE,IGUATEMI S.A.,47.058824
117,JBDU11,12319,REVISAR_NOME_DIVERGENTE,BLUE TECH SOLUTIONS EQI S.A.,47.058824
135,MLFT3,8672,REVISAR_NOME_DIVERGENTE,IGUATEMI S.A.,47.058824
118,JBDU4,12319,REVISAR_NOME_DIVERGENTE,BLUE TECH SOLUTIONS EQI S.A.,47.058824
59,CLSC6,2461,REVISAR_NOME_DIVERGENTE,CENTRAIS ELETRICAS DE SANTA CATARINA S.A,50.000000
45,BRIN3,22217,REVISAR_NOME_DIVERGENTE,ALPER CONSULTORIA E CORRETORA DE SEGUROS S.A.,50.000000
139,MPXE3,21237,REVISAR_NOME_DIVERGENTE,ENEVA S.A.,50.000000
159,PTPA4,13412,REVISAR_NOME_DIVERGENTE,ÉVORA S.A.,50.000000
44,BPNM4,21199,REVISAR_NOME_DIVERGENTE,BANCO PAN SA,50.000000
209,TRNA11,20257,REVISAR_NOME_DIVERGENTE,TRANSMISSORA ALIANÇA DE ENERGIA ELÉTRICA S.A.,52.631579
179,SGAS3,11070,REVISAR_NOME_DIVERGENTE,WLM PART. E COMÉRCIO DE MÁQUINAS E VEÍCULOS S.A.,53.333333
180,SGAS4,11070,REVISAR_NOME_DIVERGENTE,WLM PART. E COMÉRCIO DE MÁQUINAS E VEÍCULOS S.A.,53.333333
2,ABRE3,22551,REVISAR_NOME_DIVERGENTE,SOMOS EDUCAÇÃO S.A.,54.545455
1,ABRE11,22551,REVISAR_NOME_DIVERGENTE,SOMOS EDUCAÇÃO S.A.,54.545455
54,CCIM3,20486,REVISAR_NOME_DIVERGENTE,CAMARGO CORREA DESENVOLVIMENTO IMOBILIARIO SA,54.545455
221,VTLM3,21725,REVISAR_NOME_DIVERGENTE,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,54.545455
127,LLXL3,21482,REVISAR_NOME_DIVERGENTE,PRUMO LOGÍSTICA S.A.,57.142857
22,AORE3,21725,REVISAR_NOME_DIVERGENTE,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,57.142857
149,PARC3,23590,REVISAR_NOME_DIVERGENTE,WIZ CO PARTICIPAÇÕES E CORRETAGEM DE SEGUROS S.A.,58.333333
61,CMGR4,14605,REVISAR_NOME_DIVERGENTE,ENERGISA MATO GROSSO-DISTRIBUIDORA DE ENERGIA S/A,60.000000
57,CIQU4,21733,REVISAR_NOME_DIVERGENTE,CIELO S.A. - INSTITUIÇÃO DE PAGAMENTO,60.000000
163,REAG3,25887,REVISAR_NOME_DIVERGENTE,ARANDU INVESTIMENTOS S.A.,60.000000
60,CMGR3,14605,REVISAR_NOME_DIVERGENTE,ENERGISA MATO GROSSO-DISTRIBUIDORA DE ENERGIA S/A,60.000000
167,RJCP3,22330,REVISAR_NOME_DIVERGENTE,RJ CAPITAL PARTNERS S.A.,63.157895
11,AGIN3,20664,REVISAR_NOME_DIVERGENTE,AGRA EMPREENDIMENTOS IMOBILIÁRIOS S/A,63.157895
87,EQPA3,18309,REVISAR_NOME_DIVERGENTE,EQUATORIAL PARÁ DISTRIBUIDORA DE ENERGIA S.A.,66.666667
90,FFTL4,14028,REVISAR_NOME_DIVERGENTE,VALE FERTILIZANTES S.A.,66.666667
89,EQPA7,18309,REVISAR_NOME_DIVERGENTE,EQUATORIAL PARÁ DISTRIBUIDORA DE ENERGIA S.A.,66.666667
41,BPAC11,22616,REVISAR_NOME_DIVERGENTE,BANCO BTG PACTUAL S/A,66.666667
42,BPAC3,22616,REVISAR_NOME_DIVERGENTE,BANCO BTG PACTUAL S/A,66.666667
212,UCOP4,12220,REVISAR_NOME_DIVERGENTE,COSTA PINTO S.A.,66.666667
214,UOLL4,19887,REVISAR_NOME_DIVERGENTE,UNIVERSO ONLINE SA,66.666667
138,MODL4,25755,REVISAR_NOME_DIVERGENTE,BANCO MODAL S.A.,66.666667
94,FTRX4,5827,REVISAR_NOME_DIVERGENTE,MASSA FALIDA DA FÁBRICA DE TECIDOS CARLOS RENAUX S.A.,66.666667
88,EQPA5,18309,REVISAR_NOME_DIVERGENTE,EQUATORIAL PARÁ DISTRIBUIDORA DE ENERGIA S.A.,66.666667
183,SJOS4,5983,REVISAR_NOME_DIVERGENTE,FIACAO E TECELAGEM SAO JOSE S/A - EM RECUPERAÇÃO JUDICIAL,66.666667
177,SEBB11,17906,REVISAR_NOME_DIVERGENTE,PEARSON SISTEMAS DO BRASIL S.A.,66.666667
182,SJOS3,5983,REVISAR_NOME_DIVERGENTE,FIACAO E TECELAGEM SAO JOSE S/A - EM RECUPERAÇÃO JUDICIAL,66.666667
93,FTRX3,5827,REVISAR_NOME_DIVERGENTE,MASSA FALIDA DA FÁBRICA DE TECIDOS CARLOS RENAUX S.A.,66.666667
43,BPAC5,22616,REVISAR_NOME_DIVERGENTE,BANCO BTG PACTUAL S/A,66.666667
141,MTIG3,8605,REVISAR_NOME_DIVERGENTE,METALGRAFICA IGUACU SA,70.588235
142,MTIG4,8605,REVISAR_NOME_DIVERGENTE,METALGRAFICA IGUACU SA,70.588235
78,DUQE4,8648,REVISAR_NOME_DIVERGENTE,METALURGICA DUQUE SA - EM RECUPERAÇÃO JUDICIAL,71.428571
39,BNBR4,1228,REVISAR_NOME_DIVERGENTE,BANCO DO NORDESTE DO BRASIL SA,72.727273
208,TNLP4,17655,REVISAR_NOME_DIVERGENTE,TELE NORTE LESTE PARTICIPAÇÕES SA,72.727273
207,TNLP3,17655,REVISAR_NOME_DIVERGENTE,TELE NORTE LESTE PARTICIPAÇÕES SA,72.727273
217,VIGR3,22772,REVISAR_NOME_DIVERGENTE,VIGOR ALIMENTOS S.A.,75.000000
32,BICB3,21113,REVISAR_NOME_DIVERGENTE,BANK OF CHINA (BRASIL) BANCO MÚLTIPLO S.A.,75.000000
74,DHBI4,5150,REVISAR_NOME_DIVERGENTE,DHB IND E COMERCIO SA,75.000000
33,BICB4,21113,REVISAR_NOME_DIVERGENTE,BANK OF CHINA (BRASIL) BANCO MÚLTIPLO S.A.,75.000000
28,AZTE3,27626,REVISAR_NOME_DIVERGENTE,AZEVEDO & TRAVASSOS ENERGIA S.A.,77.777778

## Passo 4 — Consolidar `status_final`

Junta as duas camadas num único dataframe `auditoria_final`, com `status_final` para todos os tickers da tabela original. Ainda sem gerar arquivo — só o print do resumo geral e da lista consolidada de quem precisa de checagem manual.

In [64]:
mapa_layer2 = pendentes_pos_fca.set_index("TICKER")[["status_layer2", "DENOM_SOCIAL", "score_nome_cadastro"]]

auditoria_final = auditoria.merge(mapa_layer2, on="TICKER", how="left")


def status_consolidado(row):
    if row["status_layer1"] == "ALTA":
        return "ALTA_VIA_FCA"
    return row["status_layer2"]


auditoria_final["status_final"] = auditoria_final.apply(status_consolidado, axis=1)

print(auditoria_final["status_final"].value_counts())

n_revisar = auditoria_final["status_final"].isin(["REVISAR_NOME_DIVERGENTE", "REVISAR_CODIGO_INEXISTENTE"]).sum()
print(f"\nValidados automaticamente: {len(auditoria_final) - n_revisar} de {len(auditoria_final)} "
      f"({(len(auditoria_final) - n_revisar) / len(auditoria_final):.1%})")

colunas_master = ["TICKER", "codigo_cvm", "codigo_isin", "primeiro_ano_observado",
                   "ultimo_ano_observado", "status_final", "DENOM_SOCIAL", "score_nome_cadastro"]
colunas_master = [c for c in colunas_master if c in auditoria_final.columns]

revisar = auditoria_final[auditoria_final["status_final"].isin(
    ["REVISAR_NOME_DIVERGENTE", "REVISAR_CODIGO_INEXISTENTE"]
)].sort_values("score_nome_cadastro")

print(f"\n--- {len(revisar)} tickers para checagem manual pontual ---")
revisar[colunas_master]

status_final
ALTA_VIA_FCA                  544
ALTA_VIA_CADASTRO             140
REVISAR_NOME_DIVERGENTE        84
REVISAR_CODIGO_INEXISTENTE      1
Name: count, dtype: int64

Validados automaticamente: 684 de 769 (88.9%)

--- 85 tickers para checagem manual pontual ---

,TICKER,codigo_cvm,codigo_isin,primeiro_ano_observado,ultimo_ano_observado,status_final,DENOM_SOCIAL,score_nome_cadastro
553,PPLA11,80152,BRPPLAUNT007,2017,2022,REVISAR_CODIGO_INEXISTENTE,NaN,0.000000
743,VIVO4,17671,BRVIVOACNPR8,2010,2011,REVISAR_NOME_DIVERGENTE,TELEFÔNICA BRASIL S.A.,25.000000
742,VIVO3,17671,BRVIVOACNOR1,2010,2011,REVISAR_NOME_DIVERGENTE,TELEFÔNICA BRASIL S.A.,25.000000
272,ECOD3,20354,BRECODACNOR8,2010,2011,REVISAR_NOME_DIVERGENTE,TERRA SANTA AGRO S.A.,28.571429
690,TIBR5,11398,BRTIBRACNPA3,2010,2015,REVISAR_NOME_DIVERGENTE,TRONOX PIGMENTOS DO BRASIL S.A.,30.000000
691,TIBR6,11398,BRTIBRACNPB1,2010,2014,REVISAR_NOME_DIVERGENTE,TRONOX PIGMENTOS DO BRASIL S.A.,30.000000
447,LVTC3,25895,BRLVTCACNOR4,2021,2025,REVISAR_NOME_DIVERGENTE,LIVETECH DA BAHIA INDÚSTRIA E COMÉRCIO S.A.,33.333333
3,ABNB3,20028,BRABNBACNOR4,2010,2010,REVISAR_NOME_DIVERGENTE,VALID SOLUÇÕES S.A.,33.333333
513,OHLB3,19771,BROHLBACNOR6,2010,2012,REVISAR_NOME_DIVERGENTE,ARTERIS S.A.,33.333333
756,WDCN3,25895,BRWDCNACNOR2,2025,2025,REVISAR_NOME_DIVERGENTE,LIVETECH DA BAHIA INDÚSTRIA E COMÉRCIO S.A.,33.333333
661,SWET3,21725,BRSWETACNOR3,2015,2016,REVISAR_NOME_DIVERGENTE,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,36.363636
346,GLOB3,6505,BRGLOBACNOR8,2010,2012,REVISAR_NOME_DIVERGENTE,GRUPO CASAS BAHIA S.A.,36.363636
149,BTTL4,15458,BRBTTLACNPR7,2010,2018,REVISAR_NOME_DIVERGENTE,EMBPAR PARTICIPAÇÕES S/A,36.363636
148,BTTL3,15458,BRBTTLACNOR0,2010,2021,REVISAR_NOME_DIVERGENTE,EMBPAR PARTICIPAÇÕES S/A,36.363636
9,ADMF3,27634,BRADMFACNOR3,2025,2025,REVISAR_NOME_DIVERGENTE,B100 S.A.,37.500000
420,KROT3,17973,BRKROTACNOR9,2012,2019,REVISAR_NOME_DIVERGENTE,COGNA EDUCAÇÃO S.A.,40.000000
419,KROT11,17973,BRKROTCDAM11,2010,2012,REVISAR_NOME_DIVERGENTE,COGNA EDUCAÇÃO S.A.,40.000000
663,SZPQ4,4057,BRSZPQACNPR5,2010,2010,REVISAR_NOME_DIVERGENTE,SOUZA CRUZ SA,40.000000
370,HRTP3,22187,BRHRTPACNOR2,2010,2015,REVISAR_NOME_DIVERGENTE,PRIO S.A.,40.000000
590,RNAR3,19658,BRRNARACNOR6,2010,2015,REVISAR_NOME_DIVERGENTE,MASSA FALIDA DE POMIFRUTAS S/A,40.000000
256,DMMO3,23493,BRDMMOACNOR0,2017,2022,REVISAR_NOME_DIVERGENTE,PRIO FORTE S.A.,40.000000
430,LFFE3,12262,BRLFFEACNOR2,2016,2017,REVISAR_NOME_DIVERGENTE,JPSP INVESTIMENTOS E PARTICIPAÇÕES S.A.,41.666667
143,BRTO4,11312,BRBRTOACNPR5,2010,2012,REVISAR_NOME_DIVERGENTE,OI S.A. - EM RECUPERAÇÃO JUDICIAL,41.666667
142,BRTO3,11312,BRBRTOACNOR8,2010,2012,REVISAR_NOME_DIVERGENTE,OI S.A. - EM RECUPERAÇÃO JUDICIAL,41.666667
653,STLB3,21725,BRSTLBACNOR2,2010,2010,REVISAR_NOME_DIVERGENTE,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,41.666667
431,LFFE4,12262,BRLFFEACNPR9,2017,2017,REVISAR_NOME_DIVERGENTE,JPSP INVESTIMENTOS E PARTICIPAÇÕES S.A.,41.666667
527,PCAR5,14826,BRPCARACNPA6,2010,2011,REVISAR_NOME_DIVERGENTE,COMPANHIA BRASILEIRA DE DISTRIBUIÇÃO,43.478261
109,BNCA3,1023,BRBNCAACNOR2,2010,2010,REVISAR_NOME_DIVERGENTE,BANCO DO BRASIL S.A.,44.444444
511,OGSA3,23493,BROGSAACNOR5,2017,2017,REVISAR_NOME_DIVERGENTE,PRIO FORTE S.A.,44.444444
671,TBLE3,17329,BRTBLEACNOR2,2010,2016,REVISAR_NOME_DIVERGENTE,ENGIE BRASIL ENERGIA S.A.,44.444444
26,ALLL4,17450,BRALLLACNPR3,2010,2010,REVISAR_NOME_DIVERGENTE,RUMO S.A.,46.153846
24,ALLL11,17450,BRALLLCDAM10,2010,2010,REVISAR_NOME_DIVERGENTE,RUMO S.A.,46.153846
25,ALLL3,17450,BRALLLACNOR6,2010,2015,REVISAR_NOME_DIVERGENTE,RUMO S.A.,46.153846
392,INET3,15423,BRINETACNOR3,2010,2014,REVISAR_NOME_DIVERGENTE,FICTOR ALIMENTOS S.A. - EM RECUPERAÇÃO JUDICIAL,46.153846
471,MLFT4,8672,BRMLFTACNPR3,2010,2017,REVISAR_NOME_DIVERGENTE,IGUATEMI S.A.,47.058824
404,JBDU11,12319,BRJBDUA03OR3,2019,2019,REVISAR_NOME_DIVERGENTE,BLUE TECH SOLUTIONS EQI S.A.,47.058824
470,MLFT3,8672,BRMLFTACNOR6,2011,2011,REVISAR_NOME_DIVERGENTE,IGUATEMI S.A.,47.058824
406,JBDU4,12319,BRJBDUACNPR3,2010,2021,REVISAR_NOME_DIVERGENTE,BLUE TECH SOLUTIONS EQI S.A.,47.058824
197,CLSC6,2461,BRCLSCACNPB7,2010,2011,REVISAR_NOME_DIVERGENTE,CENTRAIS ELETRICAS DE SANTA CATARINA S.A,50.000000
129,BRIN3,22217,BRBRINACNOR3,2010,2018,REVISAR_NOME_DIVERGENTE,ALPER CONSULTORIA E CORRETORA DE SEGUROS S.A.,50.000000
484,MPXE3,21237,BRMPXEACNOR2,2010,2013,REVISAR_NOME_DIVERGENTE,ENEVA S.A.,50.000000
564,PTPA4,13412,BRPTPAACNPR8,2010,2015,REVISAR_NOME_DIVERGENTE,ÉVORA S.A.,50.000000
117,BPNM4,21199,BRBPNMACNPR6,2010,2014,REVISAR_NOME_DIVERGENTE,BANCO PAN SA,50.000000
712,TRNA11,20257,BRTRNACDAM14,2010,2012,REVISAR_NOME_DIVERGENTE,TRANSMISSORA ALIANÇA DE ENERGIA ELÉTRICA S.A.,52.631579
622,SGAS3,11070,BRSGASACNOR6,2010,2016,REVISAR_NOME_DIVERGENTE,WLM PART. E COMÉRCIO DE MÁQUINAS E VEÍCULOS S.A.,53.333333
623,SGAS4,11070,BRSGASACNPR3,2010,2017,REVISAR_NOME_DIVERGENTE,WLM PART. E COMÉRCIO DE MÁQUINAS E VEÍCULOS S.A.,53.333333
5,ABRE3,22551,BRABREACNOR9,2014,2015,REVISAR_NOME_DIVERGENTE,SOMOS EDUCAÇÃO S.A.,54.545455
4,ABRE11,22551,BRABRECDAM15,2011,2014,REVISAR_NOME_DIVERGENTE,SOMOS EDUCAÇÃO S.A.,54.545455
162,CCIM3,20486,BRCCIMACNOR5,2010,2012,REVISAR_NOME_DIVERGENTE,CAMARGO CORREA DESENVOLVIMENTO IMOBILIARIO SA,54.545455
749,VTLM3,21725,BRVTLMACNOR3,2016,2016,REVISAR_NOME_DIVERGENTE,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,54.545455
440,LLXL3,21482,BRLLXLACNOR8,2010,2014,REVISAR_NOME_DIVERGENTE,PRUMO LOGÍSTICA S.A.,57.142857
45,AORE3,21725,BRAOREACNOR2,2011,2015,REVISAR_NOME_DIVERGENTE,ADVANCED DIGITAL HEALTH MEDICINA PREVENTIVA S.A.,57.142857
521,PARC3,23590,BRPARCACNOR3,2015,2017,REVISAR_NOME_DIVERGENTE,WIZ CO PARTICIPAÇÕES E CORRETAGEM DE SEGUROS S.A.,58.333333
199,CMGR4,14605,BRCMGRACNPR4,2010,2014,REVISAR_NOME_DIVERGENTE,ENERGISA MATO GROSSO-DISTRIBUIDORA DE ENERGIA S/A,60.000000
192,CIQU4,21733,BRCIQUACNPR5,2010,2015,REVISAR_NOME_DIVERGENTE,CIELO S.A. - INSTITUIÇÃO DE PAGAMENTO,60.000000
581,REAG3,25887,BRREAGACNOR8,2025,2025,REVISAR_NOME_DIVERGENTE,ARANDU INVESTIMENTOS S.A.,60.000000
198,CMGR3,14605,BRCMGRACNOR7,2010,2014,REVISAR_NOME_DIVERGENTE,ENERGISA MATO GROSSO-DISTRIBUIDORA DE ENERGIA S/A,60.000000
588,RJCP3,22330,BRRJCPACNOR4,2011,2015,REVISAR_NOME_DIVERGENTE,RJ CAPITAL PARTNERS S.A.,63.157895
18,AGIN3,20664,BRAGINACNOR8,2010,2010,REVISAR_NOME_DIVERGENTE,AGRA EMPREENDIMENTOS IMOBILIÁRIOS S/A,63.157895
304,EQPA3,18309,BREQPAACNOR1,2020,2025,REVISAR_NOME_DIVERGENTE,EQUATORIAL PARÁ DISTRIBUIDORA DE ENERGIA S.A.,66.666667
319,FFTL4,14028,BRFFTLACNPR7,2010,2011,REVISAR_NOME_DIVERGENTE,VALE FERTILIZANTES S.A.,66.666667
306,EQPA7,18309,BREQPAACNPC0,2020,2021,REVISAR_NOME_DIVERGENTE,EQUATORIAL PARÁ DISTRIBUIDORA DE ENERGIA S.A.,66.666667
112,BPAC11,22616,BRBPACUNT006,2017,2025,REVISAR_NOME_DIVERGENTE,BANCO BTG PACTUAL S/A,66.666667
113,BPAC3,22616,BRBPACACNOR7,2017,2025,REVISAR_NOME_DIVERGENTE,BANCO BTG PACTUAL S/A,66.666667
722,UCOP4,12220,BRUCOPACNPR5,2010,2011,REVISAR_NOME_DIVERGENTE,COSTA PINTO S.A.,66.666667
728,UOLL4,19887,BRUOLLACNPR5,2010,2011,REVISAR_NOME_DIVERGENTE,UNIVERSO ONLINE SA,66.666667
479,MODL4,25755,BRMODLACNPR9,2021,2022,REVISAR_NOME_DIVERGENTE,BANCO MODAL S.A.,66.666667
333,FTRX4,5827,BRFTRXACNPR7,2010,2011,REVISAR_NOME_DIVERGENTE,MASSA FALIDA DA FÁBRICA DE TECIDOS CARLOS RENAUX S.A.,66.666667
305,EQPA5,18309,BREQPAACNPA4,2020,2025,REVISAR_NOME_DIVERGENTE,EQUATORIAL PARÁ DISTRIBUIDORA DE ENERGIA S.A.,66.666667
630,SJOS4,5983,BRSJOSACNPR8,2010,2010,REVISAR_NOME_DIVERGENTE,FIACAO E TECELAGEM SAO JOSE S/A - EM RECUPERAÇÃO JUDICIAL,66.666667
617,SEBB11,17906,BRSEBBCDAM13,2010,2011,REVISAR_NOME_DIVERGENTE,PEARSON SISTEMAS DO BRASIL S.A.,66.666667
629,SJOS3,5983,BRSJOSACNOR1,2010,2010,REVISAR_NOME_DIVERGENTE,FIACAO E TECELAGEM SAO JOSE S/A - EM RECUPERAÇÃO JUDICIAL,66.666667
332,FTRX3,5827,BRFTRXACNOR0,2011,2011,REVISAR_NOME_DIVERGENTE,MASSA FALIDA DA FÁBRICA DE TECIDOS CARLOS RENAUX S.A.,66.666667
114,BPAC5,22616,BRBPACACNPA0,2017,2025,REVISAR_NOME_DIVERGENTE,BANCO BTG PACTUAL S/A,66.666667
490,MTIG3,8605,BRMTIGACNOR0,2010,2012,REVISAR_NOME_DIVERGENTE,METALGRAFICA IGUACU SA,70.588235
491,MTIG4,8605,BRMTIGACNPR7,2010,2022,REVISAR_NOME_DIVERGENTE,METALGRAFICA IGUACU SA,70.588235
265,DUQE4,8648,BRDUQEACNPR2,2010,2013,REVISAR_NOME_DIVERGENTE,METALURGICA DUQUE SA - EM RECUPERAÇÃO JUDICIAL,71.428571
108,BNBR4,1228,BRBNBRACNPR5,2010,2013,REVISAR_NOME_DIVERGENTE,BANCO DO NORDESTE DO BRASIL SA,72.727273
704,TNLP4,17655,BRTNLPACNPR0,2010,2012,REVISAR_NOME_DIVERGENTE,TELE NORTE LESTE PARTICIPAÇÕES SA,72.727273
703,TNLP3,17655,BRTNLPACNOR3,2010,2012,REVISAR_NOME_DIVERGENTE,TELE NORTE LESTE PARTICIPAÇÕES SA,72.727273
737,VIGR3,22772,BRVIGRACNOR5,2012,2016,REVISAR_NOME_DIVERGENTE,VIGOR ALIMENTOS S.A.,75.000000
84,BICB3,21113,BRBICBACNOR0,2010,2015,REVISAR_NOME_DIVERGENTE,BANK OF CHINA (BRASIL) BANCO MÚLTIPLO S.A.,75.000000
254,DHBI4,5150,BRDHBIACNPR2,2010,2011,REVISAR_NOME_DIVERGENTE,DHB IND E COMERCIO SA,75.000000
85,BICB4,21113,BRBICBACNPR7,2010,2015,REVISAR_NOME_DIVERGENTE,BANK OF CHINA (BRASIL) BANCO MÚLTIPLO S.A.,75.000000
61,AZTE3,27626,BRAZTEACNOR4,2025,2025,REVISAR_NOME_DIVERGENTE,AZEVEDO & TRAVASSOS ENERGIA S.A.,77.777778

## Passo 5 — Inventário de `codigo_cvm` presentes nos arquivos DFP/ITR

Antes de cruzar com os tickers já validados, construímos um inventário de
todos os pares `(codigo_cvm, ano)` que efetivamente existem nos arquivos
parquet baixados. Usamos os arquivos "principais" (`dfp_cia_aberta_AAAA-AAAA.parquet`
e `itr_cia_aberta_AAAA-AAAA.parquet`) — eles contêm `CD_CVM`, `DT_REFER` e
`DENOM_CIA` para toda companhia com demonstrativo naquele ano, sem precisar
ler os arquivos grandes de cada tipo de demonstrativo (BPA, BPP, DRE, etc.),
já que o conjunto de `codigo_cvm` é o mesmo entre eles.

In [65]:
import duckdb

pasta_interim = pasta_anterior / "data/interim"

arquivos_principais = {
    "dfp": sorted((pasta_interim / "02_dfp_concatenated").glob("dfp_cia_aberta_*.parquet"))[0],
    "itr": sorted((pasta_interim / "02_itr_concatenated").glob("itr_cia_aberta_*.parquet"))[0],
}

# Confere que peguei o arquivo "principal" certo (o mais leve, sem sufixo de demonstrativo)
for origem, arq in arquivos_principais.items():
    print(origem, "->", arq.name)

dfp -> dfp_cia_aberta_2010-2025.parquet
itr -> itr_cia_aberta_2011-2025.parquet

Extrai, de cada arquivo, os pares únicos `(codigo_cvm, ano, denom_cia)`.
`ano` é derivado de `DT_REFER` (data de referência do demonstrativo).

In [66]:
def extrair_codigos_cvm(arquivo_parquet: Path, origem: str) -> pd.DataFrame:
    df = duckdb.sql(f"""
        SELECT DISTINCT
            CD_CVM AS codigo_cvm,
            CAST(SUBSTR(DT_REFER, 1, 4) AS INTEGER) AS ano,
            DENOM_CIA AS denom_cia
        FROM '{arquivo_parquet}'
    """).df()
    df["codigo_cvm"] = df["codigo_cvm"].astype(str).apply(normalizar_cvm)
    df["origem"] = origem
    return df


codigos_cvm_parquet = pd.concat(
    [extrair_codigos_cvm(arq, origem) for origem, arq in arquivos_principais.items()],
    ignore_index=True,
)

print(f"Total de pares (codigo_cvm, ano, origem): {len(codigos_cvm_parquet)}")
codigos_cvm_parquet.head()

Total de pares (codigo_cvm, ano, origem): 20999

  codigo_cvm   ano                                denom_cia origem
0      14451  2010   COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB    dfp
1      14613  2010  NEUMARKT TRADE AND FINANCIAL CENTER S/A    dfp
2      15334  2010                       BOMBRIL HOLDING SA    dfp
3      16195  2010                              AMERICEL SA    dfp
4      16551  2010   WTC RIO EMPREEND. E PARTICIPAÇÕES S.A.    dfp

### Códigos CVM únicos

Lista consolidada de todo `codigo_cvm` que aparece em pelo menos um
demonstrativo (DFP ou ITR), independentemente do ano — é o universo total
de companhias com dados financeiros disponíveis nos parquet.

In [67]:
codigos_cvm_unicos = (
    codigos_cvm_parquet
    .groupby("codigo_cvm")
    .agg(
        primeiro_ano_dfp_itr=("ano", "min"),
        ultimo_ano_dfp_itr=("ano", "max"),
        anos_disponiveis=("ano", lambda s: sorted(set(s))),
        origens=("origem", lambda s: sorted(set(s))),
        denom_cia_mais_recente=("denom_cia", "last"),
    )
    .reset_index()
)

print(f"Total de codigo_cvm únicos nos arquivos DFP/ITR: {len(codigos_cvm_unicos)}")
codigos_cvm_unicos

Total de codigo_cvm únicos nos arquivos DFP/ITR: 1228

,codigo_cvm,primeiro_ano_dfp_itr,ultimo_ano_dfp_itr,anos_disponiveis,origens,denom_cia_mais_recente
0,1023,2010,2025,"[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2...","[dfp, itr]",BCO BRASIL S.A.
1,10456,2010,2025,"[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2...","[dfp, itr]",ALPARGATAS S.A.
2,10472,2010,2023,"[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2...","[dfp, itr]",SARAIVA LIVREIROS S.A. - EM RECUPERAÇÃO JUDICIAL
3,10561,2010,2025,"[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2...","[dfp, itr]",SEIVA S.A. - FLORESTAS E INDÚSTRIAS
4,10596,2010,2013,"[2010, 2011, 2012, 2013]","[dfp, itr]",SERGEN SERVS GERAIS DE ENG SA
...,...,...,...,...,...,...
1223,9717,2010,2025,"[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2...","[dfp, itr]",PORTUENSE FERRAGENS S/A
1224,9784,2010,2011,"[2010, 2011]","[dfp, itr]",PRONOR PETROQUIMICA SA
1225,9857,2010,2012,"[2010, 2011, 2012]","[dfp, itr]",QGN PARTICIPAÇÕES SA
1226,9954,2010,2025,"[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2...","[dfp, itr]",ALFA HOLDINGS S.A.
1227,9989,2010,2025,"[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2...","[dfp, itr]",REFINARIA DE PETROLEOS MANGUINHOS S.A.

## Passo 6 — Cruzar tickers validados com a cobertura DFP/ITR

Para cada ticker com `status_final` já resolvido (`ALTA_VIA_FCA` ou
`ALTA_VIA_CADASTRO`), verificamos:

1. se o `codigo_cvm` existe em algum ano nos parquet (`tem_demonstrativo`);
2. se existe demonstrativo **dentro do período em que o ticker foi
   negociado** (`primeiro_ano_observado`–`ultimo_ano_observado`) — o que
   importa de fato para montar indicadores;
3. quantos anos de demonstrativo existem nesse período
   (`anos_cobertos_no_periodo`).

Isso separa dois problemas diferentes: `codigo_cvm` correto mas **sem**
demonstrativo no período (situação real de dados faltantes) versus
`codigo_cvm` correto e coberto (pronto para uso).

In [68]:
validados = auditoria_final[
    auditoria_final["status_final"].isin(["ALTA_VIA_FCA", "ALTA_VIA_CADASTRO"])
].copy()

mapa_anos_por_cvm = codigos_cvm_unicos.set_index("codigo_cvm")["anos_disponiveis"].to_dict()


def cobertura_dfp_itr(row):
    anos_disponiveis = mapa_anos_por_cvm.get(row["codigo_cvm_norm"])
    if anos_disponiveis is None:
        return pd.Series({
            "tem_demonstrativo": False,
            "anos_cobertos_no_periodo": [],
            "qtd_anos_cobertos_no_periodo": 0,
        })

    anos_no_periodo = [
        ano for ano in anos_disponiveis
        if row["primeiro_ano_observado"] <= ano <= row["ultimo_ano_observado"]
    ]

    return pd.Series({
        "tem_demonstrativo": True,
        "anos_cobertos_no_periodo": anos_no_periodo,
        "qtd_anos_cobertos_no_periodo": len(anos_no_periodo),
    })


validados = pd.concat([validados, validados.apply(cobertura_dfp_itr, axis=1)], axis=1)

print("Tem ao menos 1 ano de demonstrativo no período observado:",
      (validados["qtd_anos_cobertos_no_periodo"] > 0).sum(), "de", len(validados))

print("\nSem NENHUM demonstrativo (mesmo fora do período):",
      (~validados["tem_demonstrativo"]).sum())

print("\nTem demonstrativo, mas fora do período observado do ticker:",
      ((validados["tem_demonstrativo"]) & (validados["qtd_anos_cobertos_no_periodo"] == 0)).sum())

Tem ao menos 1 ano de demonstrativo no período observado: 673 de 684

Sem NENHUM demonstrativo (mesmo fora do período): 11

Tem demonstrativo, mas fora do período observado do ticker: 0

### Casos sem cobertura — merecem checagem

Tickers com `codigo_cvm` validado, mas sem demonstrativo disponível no
período em que foram negociados. Esses são os que, na prática, ficarão sem
indicador fundamentalista mesmo com o código correto.

In [69]:
sem_cobertura = validados[validados["qtd_anos_cobertos_no_periodo"] == 0][
    ["TICKER", "codigo_cvm", "status_final", "primeiro_ano_observado",
     "ultimo_ano_observado", "tem_demonstrativo"]
].sort_values("TICKER")

print(f"--- {len(sem_cobertura)} tickers sem cobertura DFP/ITR no período observado ---")
sem_cobertura

--- 11 tickers sem cobertura DFP/ITR no período observado ---

,TICKER,codigo_cvm,status_final,primeiro_ano_observado,ultimo_ano_observado,tem_demonstrativo
6,ABYA3,20206,ALTA_VIA_CADASTRO,2010,2010,False
7,ACGU3,20940,ALTA_VIA_CADASTRO,2010,2010,False
17,AGEI3,21911,ALTA_VIA_CADASTRO,2010,2010,False
55,AVIL3,108,ALTA_VIA_CADASTRO,2010,2011,False
359,GVTT3,20117,ALTA_VIA_CADASTRO,2010,2010,False
422,KSSA3,20249,ALTA_VIA_CADASTRO,2010,2010,False
452,MARI3,20761,ALTA_VIA_CADASTRO,2010,2010,False
459,MEDI3,20273,ALTA_VIA_CADASTRO,2010,2010,False
719,TVIT3,21768,ALTA_VIA_CADASTRO,2010,2010,False
761,WISA3,14397,ALTA_VIA_CADASTRO,2011,2012,False
762,WISA4,14397,ALTA_VIA_CADASTRO,2011,2012,False

## Passo 7 — Exportação final

Consolida tudo (status de auditoria + cobertura DFP/ITR) e exporta:

- `auditoria_codigo_cvm_completa.csv`: todos os 769 tickers, com status
  final e indicadores de cobertura.
- `auditoria_codigo_cvm_para_revisao.csv`: apenas os casos que restaram
  para checagem manual (nome divergente / código inexistente), do mais
  duvidoso ao menos duvidoso.
- `codigo_cvm_unicos_dfp_itr.csv`: lista de referência com todo `codigo_cvm`
  disponível nos parquet — útil depois para localizar rapidamente os dados
  de uma empresa sem precisar escanear os arquivos grandes de novo.

In [70]:
pasta_saida = pasta_anterior / "data/interim"

# 1. Junta cobertura DFP/ITR de volta no dataframe completo (quem não foi
#    validado nesta etapa fica com NaN nessas colunas — é esperado)
colunas_cobertura = ["TICKER", "tem_demonstrativo", "qtd_anos_cobertos_no_periodo"]

auditoria_export = auditoria_final.merge(
    validados[colunas_cobertura], on="TICKER", how="left"
)

# 2. Arquivo completo
colunas_finais = [
    "TICKER", "codigo_cvm", "codigo_isin", "primeiro_ano_observado",
    "ultimo_ano_observado", "status_final", "DENOM_SOCIAL",
    "score_nome_cadastro", "tem_demonstrativo", "qtd_anos_cobertos_no_periodo",
]
colunas_finais = [c for c in colunas_finais if c in auditoria_export.columns]

auditoria_export[colunas_finais].to_csv(
    pasta_saida / "07_audit/complete_code_cvm.csv", sep=";", index=False
)

# 3. Arquivo apenas com pendências de revisão manual
revisar_export = auditoria_export[
    auditoria_export["status_final"].isin(["REVISAR_NOME_DIVERGENTE", "REVISAR_CODIGO_INEXISTENTE"])
].sort_values("score_nome_cadastro")

revisar_export[colunas_finais].to_csv(
    pasta_saida / "07_audit/revision_code_cvm.csv", sep=";", index=False
)

# 4. Lista de referência de codigo_cvm disponíveis nos parquet
codigos_cvm_unicos.to_csv(
    pasta_saida / "07_audit/unique_code_cvm_for_dfp-itr.csv", sep=";", index=False
)

print("Exportado:")
print(" -", pasta_saida / "07_audit/complete_code_cvm.csv", f"({len(auditoria_export)} linhas)")
print(" -", pasta_saida / "07_audit/revision_code_cvm.csv", f"({len(revisar_export)} linhas)")
print(" -", pasta_saida / "07_audit/unique_code_cvm_for_dfp-itr.csv", f"({len(codigos_cvm_unicos)} linhas)")

Exportado:
 - c:\Users\paulo\Desktop\Python\brazilian_financial_database\data\interim\07_audit\complete_code_cvm.csv (769 linhas)
 - c:\Users\paulo\Desktop\Python\brazilian_financial_database\data\interim\07_audit\revision_code_cvm.csv (85 linhas)
 - c:\Users\paulo\Desktop\Python\brazilian_financial_database\data\interim\07_audit\unique_code_cvm_for_dfp-itr.csv (1228 linhas)